export const ApiErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TENANT_NOT_RESOLVED: "TENANT_NOT_RESOLVED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RELATION_NOT_FOUND: "RELATION_NOT_FOUND",
  RELATION_REQUIRED: "RELATION_REQUIRED",
  RELATION_DELETE_RESTRICTED: "RELATION_DELETE_RESTRICTED",
  QUERY_VALIDATION_ERROR: "QUERY_VALIDATION_ERROR",
  QUERY_UNSUPPORTED: "QUERY_UNSUPPORTED",
  QUERY_FORBIDDEN: "QUERY_FORBIDDEN",
  QUERY_ON_ENCRYPTED_FIELD: "QUERY_ON_ENCRYPTED_FIELD",
  COMPOSITE_INDEX_REQUIRED: "COMPOSITE_INDEX_REQUIRED",
  INDEX_CREATING: "INDEX_CREATING",
  INDEX_PROVISIONING_FAILED: "INDEX_PROVISIONING_FAILED",
  SEARCH_NOT_CONFIGURED: "SEARCH_NOT_CONFIGURED",
  INVALID_CURSOR: "INVALID_CURSOR",
  QUERY_TOO_BROAD: "QUERY_TOO_BROAD",
  METRIC_ROW_NOT_FOUND: "METRIC_ROW_NOT_FOUND",
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];

export interface ApiErrorBody {
  readonly code: ApiErrorCode;
  readonly message: string;
  readonly details?: unknown;
}

export interface ApiEnvelope<T> {
  readonly data: T | null;
  readonly error: ApiErrorBody | null;
}
