export { formatHookEvent, parseHookEvent, isBeforePhase } from "./event.js";
export {
  compileDataHook,
  runDataHook,
  evaluateCondition,
  evaluateConditionNode,
} from "./interpret-data-hook.js";
export {
  createHookEntityServices,
  type DispatchChainedHooksParams,
  type HookEntityAccessControl,
  type HookFieldAccessLevel,
  type HookRecordMutatedInput,
  type HookRecordMutatedOperation,
} from "./create-hook-entity-services.js";
export { runQueuedDataHookJob } from "./run-queued-data-hook-job.js";
export {
  dataHookJobPayloadSchema,
  buildDataHookJobPayload,
  dataHookJobPayloadToUser,
} from "./data-hook-job.js";
export {
  registerSystemHook,
  registerDynamicHook,
  unregisterDynamicHook,
  invalidateTenantHookCache,
  getHooksForEvent,
  getAllRegisteredSystemHooks,
  clearHookRegistry,
  executeHooks,
  executeHooks as emitHooks,
  registerHook,
  clearSystemHookRegistry,
} from "./registry.js";
export {
  validateDataHookEntity,
  validateDataHookActions,
  validateDataHookCondition,
  validateCreateDataHookInput,
  validatePatchDataHookInput,
} from "./validate-data-hook.js";
export {
  DATA_HOOKS_COLLECTION,
  DATA_HOOK_OPERATIONS,
  DATA_HOOK_JOB_OPERATIONS,
  DATA_HOOK_PHASES,
  DATA_HOOK_EXECUTION_MODES,
  DATA_HOOK_CONDITION_OPERATORS,
  DATA_HOOK_CONDITION_COMBINATORS,
  DATA_HOOK_TRIGGER_KINDS,
  DATA_HOOK_SCHEDULE_SCOPES,
  VALUELESS_CONDITION_OPERATORS,
  dataHookTriggerSchema,
  dataHookCrudTriggerSchema,
  dataHookScheduleTriggerSchema,
  dataHookEmailTriggerSchema,
  isScheduleTrigger,
  isEmailTrigger,
  isCrudTrigger,
  listCrudOperations,
  resolveCrudUpdateFields,
  emailTriggerAppliesToBinding,
  dataHookConditionSchema,
  dataHookUpdateMatchingWhereSchema,
  dataHookConditionLeafSchema,
  dataHookConditionNodeSchema,
  dataHookDefinitionConditionSchema,
  dataHookActionSchema,
  dataHookDefinitionSchema,
  createDataHookInputSchema,
  patchDataHookInputSchema,
  actionTargetEntities,
  MAX_LOADED_RECORDS,
  MAX_CALL_AI_INCLUDE_ENTITIES,
  DEFAULT_MATCH_SIMILAR_MIN_SCORE,
  MAX_AGGREGATE_ACTIONS,
  MAX_CREATE_RECORDS,
  MAX_CREATE_RECORDS_QUEUED,
  DATA_HOOK_AGGREGATE_OPERATORS,
  DATA_HOOK_LOADED_ALIAS_PATTERN,
} from "./data-hook-definition.js";
export { computeAggregateMatching } from "./aggregate-matching-utils.js";
export {
  aliasesFromFieldValue,
  pickBestAliasMatch,
} from "./match-related-record-utils.js";
export {
  cosineSimilarity,
  pickBestEmbeddingMatch,
  readNumericArrayField,
} from "./match-similar-record-utils.js";
export {
  MAX_SCHEDULED_RECORDS_PER_RUN,
  SCHEDULED_HOOK_SENTINEL_ID,
  buildScheduledHookContext,
  buildSyntheticScheduledRecord,
  getScheduleScope,
  getScheduleTimezone,
  isCronDueNow,
  listDueScheduledHooks,
  validateCronExpression,
  validateTimezone,
} from "./schedule-trigger-utils.js";
export {
  findUpdateMatchingLookupLeaf,
  hasUpdateMatchingLookupLeaf,
  listMatchingRecordsForWhere,
  MAX_MATCHING_RECORDS,
  normalizeUpdateMatchingWhere,
} from "./update-matching-utils.js";
export {
  extractLiteralInteger,
  resolveMaxCreateRecords,
  validateCreateRecordsLiteralCount,
  assertCreateRecordsRuntimeCount,
} from "./create-records-utils.js";
export {
  DATA_HOOK_DEFINITION_JSON_VERSION,
  DATA_HOOK_DEFINITION_JSON_KIND,
  DATA_HOOKS_CATALOG_JSON_KIND,
  catalogHookKey,
  toPortableDataHookDefinition,
  createDataHookDefinitionEnvelope,
  createDataHooksCatalogEnvelope,
  parseDataHookDefinitionJson,
  validateDataHookDefinitionImport,
  parseDataHooksCatalogJson,
  validateDataHooksCatalogImport,
  validateDataHooksCatalogEnvelope,
  computeDataHooksCatalogReplacePlan,
  dataHooksCatalogEnvelopeSchema,
} from "./data-hook-definition-json.js";
export type {
  DataHookOperation,
  DataHookPhase,
  DataHookExecutionMode,
  DataHookConditionOperator,
  DataHookConditionCombinator,
  DataHookTriggerKind,
  DataHookScheduleScope,
  DataHookJobOperation,
  DataHookTrigger,
  DataHookCrudTrigger,
  DataHookScheduleTrigger,
  DataHookEmailTrigger,
  DataHookCondition,
  DataHookConditionLeaf,
  DataHookConditionGroup,
  DataHookConditionNode,
  DataHookUpdateMatchingWhere,
  DataHookAggregateOperator,
  DataHookAction,
  DataHookDefinition,
  CreateDataHookInput,
  PatchDataHookInput,
} from "./data-hook-definition.js";
export {
  DATA_HOOK_EXECUTIONS_COLLECTION,
  DATA_HOOK_EXECUTION_STATUSES,
  DATA_HOOK_EXECUTION_TERMINAL_STATUSES,
  DATA_HOOK_EXECUTION_ACTIVE_STATUSES,
  createDataHookExecutionInputSchema,
  updateDataHookExecutionPatchSchema,
  dataHookExecutionRecordSchema,
} from "./data-hook-execution.js";
export {
  formatHookExecutionSubtitle,
  formatHookExecutionWritesSummary,
  totalHookExecutionWrites,
} from "./hook-execution-presentation.js";
export {
  MAX_HOOK_ACTION_TRACE_ENTRIES,
  entityWriteCountsSchema,
  dataHookActionTraceEntrySchema,
  dataHookExecutionMetricsSchema,
  HookWriteMetricsCollector,
  wrapHookEntityServicesWithMetrics,
  appendActionTraceEntry,
  buildExecutionMetricsSnapshot,
} from "./hook-execution-metrics.js";
export type {
  EntityWriteCounts,
  DataHookActionTraceEntry,
  DataHookExecutionMetrics,
} from "./hook-execution-metrics.js";
export type {
  DataHookExecutionStatus,
  DataHookExecutionTerminalStatus,
  DataHookExecutionActiveStatus,
  DataHookExecutionBaseFields,
  CreateDataHookExecutionInput,
  UpdateDataHookExecutionPatch,
  DataHookExecutionRecord,
  DataHookExecutionRecorder,
} from "./data-hook-execution.js";
export type { DataHookJobPayload } from "./data-hook-job.js";
export type {
  DataHookDefinitionJsonError,
  PortableDataHookDefinition,
  DataHookDefinitionFormData,
  DataHooksCatalogEnvelope,
  DataHooksCatalogReplacePlan,
} from "./data-hook-definition-json.js";
export {
  EXPRESSION_BINARY_OPERATORS,
  EXPRESSION_UNARY_OPERATORS,
  EXPRESSION_FUNCTIONS,
  EXPRESSION_VARIABLES,
  DATE_UNITS,
  MAX_SWITCH_CASES,
  MAX_FORMULA_DEPTH,
  MAX_ARRAY_LITERAL_ITEMS,
  MAX_CALL_ARGS,
  expressionNodeSchema,
  evaluateExpression,
  walkExpressionNodes,
  collectFormulaNames,
  expressionValuesEqual,
  isEmptyExpressionValue,
  isTruthyExpressionValue,
  normalizeMatchText,
  normalizeMerchantText,
  isArrayLiteralNode,
  ExpressionEvaluationError,
} from "./expression.js";
export {
  EXPRESSION_FUNCTION_SPECS,
  getExpressionFunctionSpec,
  listExpressionFunctionSpecs,
} from "./expression-function-spec.js";
export type {
  ExpressionFunctionArgKind,
  ExpressionFunctionArgSpec,
  ExpressionFunctionSpec,
} from "./expression-function-spec.js";
export type {
  ExpressionBinaryOperator,
  ExpressionUnaryOperator,
  ExpressionFunction,
  ExpressionVariable,
  DateUnit,
  ExpressionValue,
  ExpressionScalar,
  ExpressionLiteralValue,
  ExpressionNode,
  ExpressionSwitchCase,
  ExpressionScope,
  FormulaDefinitionForEval,
  FormulaResolver,
} from "./expression.js";
export { HOOK_PERMISSIONS } from "./permissions.js";
export {
  HOOK_OPERATIONS,
  HOOK_PHASES,
  HookExecutionError,
  DataHookSkipError,
} from "./types.js";
export type {
  HookOperation,
  HookPhase,
  ParsedHookEvent,
  HookUser,
  HookEntityRecord,
  HookEntityListQuery,
  HookEntityRuntime,
  HookEntityWriteOptions,
  HookEntityServices,
  HookLogger,
  HookServices,
  HookContext,
  DataHookWebhookRequest,
  DataHookAiRequest,
  DataHookEmbeddingRequest,
  DataHookRecordAiSummaryRequest,
  DataHookRecordAiSummaryResult,
  DataHookUpsertAiRecordContextRequest,
  DataHookUpsertAiRecordContextResult,
  DataHookEnqueueAiRecordNarrativeRequest,
  DataHookInvalidateAiRecordNarrativesRequest,
  DataHookRecordSummaryTemplate,
  HookHandler,
  RegisteredSystemHook,
  RegisteredDynamicHook,
  RegisteredHook,
} from "./types.js";
