import { useId, useState } from "react";
import { useTranslation } from "react-i18next";

import { Button, Checkbox, FieldLabel, Input, Text } from "@repo/ui";

import type { FieldDefinitionInput } from "../../lib/api-client";

import { FIELD_TYPES } from "./field-types";
import {
  generateRelationFieldName,
  type RelationType,
} from "./generate-relation-field-name";
import { RelationTypeInfo } from "./RelationTypeInfo";

interface FieldEditorFormProps {
  readonly field: FieldDefinitionInput;
  readonly relationTargets: readonly {
    readonly name: string;
    readonly label: string;
  }[];
  readonly onChange: (field: FieldDefinitionInput) => void;
  readonly typeReadOnly?: boolean;
  readonly orderDefault?: number;
}

function isCustomRelationName(
  field: FieldDefinitionInput,
  relationType: RelationType,
): boolean {
  if (field.type !== "relation" || !field.relation?.target) {
    return false;
  }
  return (
    field.name !==
    generateRelationFieldName(field.relation.target, relationType)
  );
}

export function FieldEditorForm({
  field,
  relationTargets,
  onChange,
  typeReadOnly = false,
  orderDefault = 0,
}: FieldEditorFormProps) {
  const { t } = useTranslation("common");
  const idPrefix = useId().replace(/:/g, "");
  const relationType = field.relation?.type ?? "many-to-one";
  const [useCustomRelationName, setUseCustomRelationName] = useState(() =>
    isCustomRelationName(field, relationType),
  );

  function update(partial: Partial<FieldDefinitionInput>) {
    onChange({ ...field, ...partial });
  }

  function updateRelation(
    partial: Partial<NonNullable<FieldDefinitionInput["relation"]>>,
  ) {
    const nextRelation = {
      target: field.relation?.target ?? "",
      type: field.relation?.type ?? "many-to-one",
      ...partial,
    };
    const generatedName = generateRelationFieldName(
      nextRelation.target,
      nextRelation.type,
    );

    update({
      relation: nextRelation,
      ...(useCustomRelationName || !nextRelation.target
        ? {}
        : { name: generatedName }),
    });
  }

  function updateUi(partial: Partial<NonNullable<FieldDefinitionInput["ui"]>>) {
    onChange({
      ...field,
      ui: {
        ...field.ui,
        ...partial,
      },
    });
  }

  const isRelationField = field.type === "relation";
  const autoGeneratedName = isRelationField
    ? generateRelationFieldName(field.relation?.target ?? "", relationType)
    : field.name;
  const nameInputValue =
    isRelationField && !useCustomRelationName ? autoGeneratedName : field.name;
  const nameInputDisabled =
    isRelationField &&
    !useCustomRelationName &&
    Boolean(field.relation?.target);

  const selectClassName =
    "border-input bg-background ring-offset-background focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2";

  return (
    <div className="space-y-4">
      <div>
        <FieldLabel htmlFor={`${idPrefix}-field-type`}>
          {t("dataModels.fieldType")}
        </FieldLabel>
        <select
          id={`${idPrefix}-field-type`}
          className={selectClassName}
          value={field.type}
          disabled={typeReadOnly}
          onChange={(event) => {
            const type = event.target.value as FieldDefinitionInput["type"];
            if (type !== "relation") {
              setUseCustomRelationName(false);
            }
            update({
              type,
              relation: type === "relation" ? field.relation : undefined,
              enumValues:
                type === "enum" ? (field.enumValues ?? [""]) : undefined,
            });
          }}
        >
          {FIELD_TYPES.map((type) => (
            <option key={type} value={type}>
              {t(`dataModels.fieldTypes.${type}`)}
            </option>
          ))}
        </select>
      </div>

      <div className="space-y-2">
        <FieldLabel htmlFor={`${idPrefix}-field-name`}>
          {t("dataModels.fieldName")}
        </FieldLabel>
        <Input
          id={`${idPrefix}-field-name`}
          value={nameInputValue}
          disabled={nameInputDisabled}
          onChange={(event) => update({ name: event.target.value })}
          placeholder="amount"
        />
        {isRelationField ? (
          <Checkbox
            id={`${idPrefix}-custom-relation-name`}
            label={t("dataModels.customRelationFieldName")}
            checked={useCustomRelationName}
            onChange={(event) => {
              const checked = event.target.checked;
              setUseCustomRelationName(checked);
              if (!checked) {
                const generatedName = generateRelationFieldName(
                  field.relation?.target ?? "",
                  relationType,
                );
                if (generatedName) {
                  update({ name: generatedName });
                }
              }
            }}
          />
        ) : null}
      </div>

      <Checkbox
        id={`${idPrefix}-field-required`}
        label={t("dataModels.required")}
        checked={field.required ?? false}
        onChange={(event) => update({ required: event.target.checked })}
      />

      <div>
        <FieldLabel htmlFor={`${idPrefix}-field-order`}>
          {t("dataModels.displayOrder")}
        </FieldLabel>
        <Input
          id={`${idPrefix}-field-order`}
          type="number"
          min={0}
          step={1}
          value={field.ui?.order ?? orderDefault}
          onChange={(event) => {
            const parsed = Number.parseInt(event.target.value, 10);
            updateUi({
              order: Number.isNaN(parsed) ? orderDefault : Math.max(0, parsed),
            });
          }}
        />
        <Text className="text-muted-foreground mt-1 text-sm">
          {t("dataModels.displayOrderHint")}
        </Text>
      </div>

      <div className="space-y-2">
        <Checkbox
          id={`${idPrefix}-field-filterable`}
          label={t("dataModels.fieldFilterable")}
          checked={field.ui?.filterable !== false}
          onChange={(event) => updateUi({ filterable: event.target.checked })}
        />
        <Text className="text-muted-foreground text-sm">
          {t("dataModels.fieldFilterableHint")}
        </Text>
      </div>

      <div className="space-y-2">
        <Checkbox
          id={`${idPrefix}-field-sortable`}
          label={t("dataModels.fieldSortable")}
          checked={field.ui?.sortable !== false}
          onChange={(event) => updateUi({ sortable: event.target.checked })}
        />
        <Text className="text-muted-foreground text-sm">
          {t("dataModels.fieldSortableHint")}
        </Text>
      </div>

      {field.type === "enum" ? (
        <div className="space-y-2">
          <FieldLabel>{t("dataModels.enumValues")}</FieldLabel>
          {(field.enumValues ?? [""]).map((value, enumIndex) => (
            <div key={enumIndex} className="flex gap-2">
              <Input
                value={value}
                onChange={(event) => {
                  const next = [...(field.enumValues ?? [""])];
                  next[enumIndex] = event.target.value;
                  update({ enumValues: next });
                }}
                placeholder={t("dataModels.enumPlaceholder")}
              />
              <Button
                type="button"
                variant="ghost"
                onClick={() => {
                  const next = [...(field.enumValues ?? [""])];
                  next.splice(enumIndex, 1);
                  update({ enumValues: next.length > 0 ? next : [""] });
                }}
              >
                {t("dataModels.removeValue")}
              </Button>
            </div>
          ))}
          <Button
            type="button"
            variant="outline"
            onClick={() =>
              update({ enumValues: [...(field.enumValues ?? [""]), ""] })
            }
          >
            {t("dataModels.addEnumValue")}
          </Button>
        </div>
      ) : null}

      {field.type === "relation" ? (
        <div className="grid gap-3 md:grid-cols-2">
          <div>
            <FieldLabel htmlFor={`${idPrefix}-relation-target`}>
              {t("dataModels.relationTarget")}
            </FieldLabel>
            <select
              id={`${idPrefix}-relation-target`}
              className={selectClassName}
              value={field.relation?.target ?? ""}
              onChange={(event) =>
                updateRelation({ target: event.target.value })
              }
            >
              <option value="">{t("dataModels.selectTarget")}</option>
              {relationTargets.map((target) => (
                <option key={target.name} value={target.name}>
                  {target.label}
                </option>
              ))}
            </select>
            <Text className="text-muted-foreground mt-1 text-sm">
              {t("dataModels.relationTargetHint")}
            </Text>
          </div>
          <div>
            <div className="mb-1.5 flex items-center gap-1.5">
              <FieldLabel htmlFor={`${idPrefix}-relation-type`}>
                {t("dataModels.relationType")}
              </FieldLabel>
              <RelationTypeInfo relationType={relationType} />
            </div>
            <select
              id={`${idPrefix}-relation-type`}
              className={selectClassName}
              value={field.relation?.type ?? "many-to-one"}
              onChange={(event) =>
                updateRelation({
                  type: event.target.value as RelationType,
                })
              }
            >
              <option value="one-to-one">one-to-one</option>
              <option value="one-to-many">one-to-many</option>
              <option value="many-to-one">many-to-one</option>
              <option value="many-to-many">many-to-many</option>
            </select>
            {relationType === "one-to-many" && field.relation?.target ? (
              <Text className="text-muted-foreground mt-2 text-sm">
                {t("dataModels.oneToManyInlineWarning", {
                  target: field.relation.target,
                })}
              </Text>
            ) : null}
          </div>
        </div>
      ) : null}

      {field.type === "number" ? (
        <div>
          <FieldLabel htmlFor={`${idPrefix}-display-format`}>
            {t("dataModels.numberDisplayFormat")}
          </FieldLabel>
          <select
            id={`${idPrefix}-display-format`}
            className={selectClassName}
            value={field.ui?.displayFormat ?? "plain"}
            onChange={(event) =>
              updateUi({
                displayFormat: event.target.value as "currency" | "plain",
              })
            }
          >
            <option value="plain">
              {t("dataModels.numberDisplayFormats.plain")}
            </option>
            <option value="currency">
              {t("dataModels.numberDisplayFormats.currency")}
            </option>
          </select>
        </div>
      ) : null}

      {field.type === "date" ? (
        <div>
          <FieldLabel htmlFor={`${idPrefix}-date-display-format`}>
            {t("dataModels.dateDisplayFormat")}
          </FieldLabel>
          <select
            id={`${idPrefix}-date-display-format`}
            className={selectClassName}
            value={field.ui?.dateDisplayFormat ?? "datetime"}
            onChange={(event) =>
              updateUi({
                dateDisplayFormat: event.target.value as
                  | "date"
                  | "datetime"
                  | "time",
              })
            }
          >
            <option value="date">
              {t("dataModels.dateDisplayFormats.date")}
            </option>
            <option value="datetime">
              {t("dataModels.dateDisplayFormats.datetime")}
            </option>
            <option value="time">
              {t("dataModels.dateDisplayFormats.time")}
            </option>
          </select>
        </div>
      ) : null}
    </div>
  );
}
