import { useId, useState } from "react";
import { useTranslation } from "react-i18next";

import {
  DEFAULT_DOCUMENT_MAX_SIZE_BYTES,
  DEFAULT_IMAGE_MAX_SIZE_BYTES,
  resolveFileFieldMaxSizeBytes,
} from "@repo/entities";
import {
  Button,
  Checkbox,
  FieldLabel,
  Input,
  PhotoUpload,
  Text,
  toast,
} from "@repo/ui";
import { AdminSelect as Select } from "~/components/admin/AdminSelect";

import type { FieldDefinitionInput } from "../../lib/api-client";
import {
  isEntityFileReferenceWithDownload,
  readFileAsBase64,
  uploadEntityFile,
} from "../../lib/entity-file-client";
import { imagePhotoUploadLabels } from "../../lib/photo-upload-labels";

import { fieldSupportsArray } from "./array-field-eligibility";
import { FIELD_TYPES } from "./field-types";
import {
  generateRelationFieldName,
  type RelationType,
} from "./generate-relation-field-name";
import { RelationTypeInfo } from "./RelationTypeInfo";
import {
  fieldSupportsListSearch,
  isFieldSearchableChecked,
} from "./field-list-search";
import { resolveFieldDefinitionName } from "./field-types";

interface FieldEditorFormProps {
  readonly field: FieldDefinitionInput;
  readonly entityName?: string;
  readonly relationTargets: readonly {
    readonly name: string;
    readonly label: string;
  }[];
  readonly onChange: (field: FieldDefinitionInput) => void;
  readonly typeReadOnly?: boolean;
  readonly orderDefault?: number;
}

function formatMaxSizeMb(bytes?: number): string {
  if (bytes === undefined) {
    return "";
  }
  const mb = bytes / (1024 * 1024);
  return Number.isInteger(mb)
    ? String(mb)
    : mb.toFixed(2).replace(/\.?0+$/, "");
}

function parseMaxSizeMb(input: string): number | undefined {
  const trimmed = input.trim();
  if (!trimmed) {
    return undefined;
  }
  const mb = Number(trimmed);
  if (!Number.isFinite(mb) || mb <= 0) {
    return undefined;
  }
  return Math.round(mb * 1024 * 1024);
}

function isCustomRelationName(
  field: FieldDefinitionInput,
  relationType: RelationType,
): boolean {
  if (field.type !== "relation" || !field.relation?.target) {
    return false;
  }
  if (!field.name.trim()) {
    return false;
  }
  return (
    field.name !==
    generateRelationFieldName(field.relation.target, relationType)
  );
}

export function FieldEditorForm({
  field,
  entityName,
  relationTargets,
  onChange,
  typeReadOnly = false,
  orderDefault = 0,
}: FieldEditorFormProps) {
  const { t } = useTranslation("common");
  const idPrefix = useId().replace(/:/g, "");
  const relationType = field.relation?.type ?? "many-to-one";
  const [useCustomRelationName, setUseCustomRelationName] = useState(() =>
    isCustomRelationName(field, relationType),
  );

  function update(partial: Partial<FieldDefinitionInput>) {
    onChange({ ...field, ...partial });
  }

  function updateRelation(
    partial: Partial<NonNullable<FieldDefinitionInput["relation"]>>,
  ) {
    const nextRelation = {
      target: field.relation?.target ?? "",
      type: field.relation?.type ?? "many-to-one",
      onDelete: field.relation?.onDelete,
      ...partial,
    };
    const generatedName = generateRelationFieldName(
      nextRelation.target,
      nextRelation.type,
    );

    update({
      relation: nextRelation,
      ...(useCustomRelationName || !nextRelation.target
        ? {}
        : { name: generatedName }),
    });
  }

  function updateUi(partial: Partial<NonNullable<FieldDefinitionInput["ui"]>>) {
    onChange({
      ...field,
      ui: {
        ...field.ui,
        ...partial,
      },
    });
  }

  const isRelationField = field.type === "relation";
  const autoGeneratedName = isRelationField
    ? generateRelationFieldName(field.relation?.target ?? "", relationType)
    : field.name;
  const nameInputValue =
    isRelationField && !useCustomRelationName ? autoGeneratedName : field.name;
  const nameInputDisabled =
    isRelationField &&
    !useCustomRelationName &&
    Boolean(field.relation?.target);

  const selectClassName =
    "border-input bg-background ring-offset-background focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2";

  return (
    <div className="space-y-4">
      <div>
        <FieldLabel htmlFor={`${idPrefix}-field-type`}>
          {t("dataModels.fieldType")}
        </FieldLabel>
        <Select
          id={`${idPrefix}-field-type`}
          className={selectClassName}
          value={field.type}
          disabled={typeReadOnly}
          onChange={(event) => {
            const type = event.target.value as FieldDefinitionInput["type"];
            setUseCustomRelationName(false);
            let ui: FieldDefinitionInput["ui"];
            if (type === "string" && field.sensitive !== true) {
              ui = {
                ...field.ui,
                searchable: field.ui?.searchable ?? true,
              };
            } else if (field.ui?.searchable !== undefined) {
              const { searchable: _removed, ...restUi } = field.ui;
              void _removed;
              ui = Object.keys(restUi).length > 0 ? restUi : undefined;
            }

            const nextIsArray =
              field.isArray === true && fieldSupportsArray(type)
                ? true
                : undefined;

            update({
              type,
              isArray: nextIsArray,
              relation:
                type === "relation"
                  ? (field.relation ?? { target: "", type: "many-to-one" })
                  : undefined,
              enumValues:
                type === "enum" ? (field.enumValues ?? [""]) : undefined,
              numberKind:
                type === "number" ? (field.numberKind ?? "decimal") : undefined,
              ...(ui !== undefined ? { ui } : {}),
              ...(nextIsArray
                ? {
                    ui: {
                      ...ui,
                      sortable: false,
                      searchable:
                        (type === "string" || type === "enum") &&
                        field.sensitive !== true,
                    },
                  }
                : {}),
            });
          }}
        >
          {FIELD_TYPES.map((type) => (
            <option key={type} value={type}>
              {t(`dataModels.fieldTypes.${type}`)}
            </option>
          ))}
        </Select>
      </div>

      <div className="space-y-2">
        <FieldLabel htmlFor={`${idPrefix}-field-name`}>
          {t("dataModels.fieldName")}
        </FieldLabel>
        <Input
          id={`${idPrefix}-field-name`}
          value={nameInputValue}
          disabled={nameInputDisabled}
          onChange={(event) => update({ name: event.target.value })}
          placeholder="amount"
        />
        {isRelationField ? (
          <Checkbox
            id={`${idPrefix}-custom-relation-name`}
            label={t("dataModels.customRelationFieldName")}
            checked={useCustomRelationName}
            onChange={(event) => {
              const checked = event.target.checked;
              setUseCustomRelationName(checked);
              if (!checked) {
                const generatedName = generateRelationFieldName(
                  field.relation?.target ?? "",
                  relationType,
                );
                if (generatedName) {
                  update({ name: generatedName });
                }
              }
            }}
          />
        ) : null}
      </div>

      <Checkbox
        id={`${idPrefix}-field-required`}
        label={t("dataModels.required")}
        checked={field.required ?? false}
        onChange={(event) => update({ required: event.target.checked })}
      />

      {fieldSupportsArray(field.type) ? (
        <div className="space-y-2">
          <Checkbox
            id={`${idPrefix}-field-is-array`}
            label={t("dataModels.fieldIsArray")}
            checked={field.isArray === true}
            onChange={(event) => {
              const isArray = event.target.checked;
              if (!isArray) {
                update({ isArray: undefined });
                return;
              }

              update({
                isArray: true,
                ui: {
                  ...field.ui,
                  sortable: false,
                  searchable:
                    (field.type === "string" || field.type === "enum") &&
                    field.sensitive !== true,
                },
              });
            }}
          />
          <Text className="text-muted-foreground text-sm">
            {t("dataModels.fieldIsArrayHint")}
          </Text>
        </div>
      ) : null}

      <div className="space-y-2">
        <Checkbox
          id={`${idPrefix}-field-sensitive`}
          label={t("dataModels.sensitive")}
          checked={field.sensitive ?? false}
          disabled={
            field.type === "relation" ||
            field.type === "image" ||
            field.type === "document"
          }
          onChange={(event) => {
            const sensitive = event.target.checked;
            update({
              sensitive,
              ...(field.type === "string"
                ? {
                    ui: {
                      ...field.ui,
                      searchable: sensitive
                        ? false
                        : (field.ui?.searchable ?? true),
                    },
                  }
                : {}),
            });
          }}
        />
        <Text className="text-muted-foreground text-sm">
          {t("dataModels.sensitiveHint")}
        </Text>
      </div>

      <div>
        <FieldLabel htmlFor={`${idPrefix}-field-order`}>
          {t("dataModels.displayOrder")}
        </FieldLabel>
        <Input
          id={`${idPrefix}-field-order`}
          type="number"
          min={0}
          step={1}
          value={field.ui?.order ?? orderDefault}
          onChange={(event) => {
            const parsed = Number.parseInt(event.target.value, 10);
            updateUi({
              order: Number.isNaN(parsed) ? orderDefault : Math.max(0, parsed),
            });
          }}
        />
        <Text className="text-muted-foreground mt-1 text-sm">
          {t("dataModels.displayOrderHint")}
        </Text>
      </div>

      <div className="space-y-2">
        <Checkbox
          id={`${idPrefix}-field-filterable`}
          label={t("dataModels.fieldFilterable")}
          checked={field.ui?.filterable !== false}
          onChange={(event) => updateUi({ filterable: event.target.checked })}
        />
        <Text className="text-muted-foreground text-sm">
          {field.isArray
            ? t("dataModels.fieldFilterableArrayHint")
            : t("dataModels.fieldFilterableHint")}
        </Text>
      </div>

      <div className="space-y-2">
        <Checkbox
          id={`${idPrefix}-field-sortable`}
          label={t("dataModels.fieldSortable")}
          checked={field.ui?.sortable !== false}
          disabled={field.isArray === true}
          onChange={(event) => updateUi({ sortable: event.target.checked })}
        />
        <Text className="text-muted-foreground text-sm">
          {field.isArray
            ? t("dataModels.fieldSortableArrayHint")
            : t("dataModels.fieldSortableHint")}
        </Text>
      </div>

      {fieldSupportsListSearch(field) ? (
        <div className="space-y-2">
          <Checkbox
            id={`${idPrefix}-field-searchable`}
            label={t("dataModels.fieldSearchable")}
            checked={isFieldSearchableChecked(field)}
            onChange={(event) => updateUi({ searchable: event.target.checked })}
          />
          <Text className="text-muted-foreground text-sm">
            {t("dataModels.fieldSearchableHint")}
          </Text>
        </div>
      ) : null}

      {field.type === "enum" ? (
        <div className="space-y-2">
          <FieldLabel>{t("dataModels.enumValues")}</FieldLabel>
          {(field.enumValues ?? [""]).map((value, enumIndex) => (
            <div key={enumIndex} className="flex gap-2">
              <Input
                value={value}
                onChange={(event) => {
                  const next = [...(field.enumValues ?? [""])];
                  next[enumIndex] = event.target.value;
                  update({ enumValues: next });
                }}
                placeholder={t("dataModels.enumPlaceholder")}
              />
              <Button
                type="button"
                variant="ghost"
                onClick={() => {
                  const next = [...(field.enumValues ?? [""])];
                  next.splice(enumIndex, 1);
                  update({ enumValues: next.length > 0 ? next : [""] });
                }}
              >
                {t("dataModels.removeValue")}
              </Button>
            </div>
          ))}
          <Button
            type="button"
            variant="outline"
            onClick={() =>
              update({ enumValues: [...(field.enumValues ?? [""]), ""] })
            }
          >
            {t("dataModels.addEnumValue")}
          </Button>
        </div>
      ) : null}

      {field.type === "relation" ? (
        <div className="grid gap-3 md:grid-cols-2">
          <div>
            <FieldLabel htmlFor={`${idPrefix}-relation-target`}>
              {t("dataModels.relationTarget")}
            </FieldLabel>
            <Select
              id={`${idPrefix}-relation-target`}
              className={selectClassName}
              value={field.relation?.target ?? ""}
              onChange={(event) =>
                updateRelation({ target: event.target.value })
              }
            >
              <option value="">{t("dataModels.selectTarget")}</option>
              {relationTargets.map((target) => (
                <option key={target.name} value={target.name}>
                  {target.label}
                </option>
              ))}
            </Select>
            <Text className="text-muted-foreground mt-1 text-sm">
              {t("dataModels.relationTargetHint")}
            </Text>
          </div>
          <div>
            <div className="mb-1.5 flex items-center gap-1.5">
              <FieldLabel htmlFor={`${idPrefix}-relation-type`}>
                {t("dataModels.relationType")}
              </FieldLabel>
              <RelationTypeInfo relationType={relationType} />
            </div>
            <Select
              id={`${idPrefix}-relation-type`}
              className={selectClassName}
              value={field.relation?.type ?? "many-to-one"}
              onChange={(event) =>
                updateRelation({
                  type: event.target.value as RelationType,
                })
              }
            >
              <option value="one-to-one">one-to-one</option>
              <option value="one-to-many">one-to-many</option>
              <option value="many-to-one">many-to-one</option>
              <option value="many-to-many">many-to-many</option>
            </Select>
            {relationType === "one-to-many" && field.relation?.target ? (
              <Text className="text-muted-foreground mt-2 text-sm">
                {t("dataModels.oneToManyInlineWarning", {
                  target: field.relation.target,
                })}
              </Text>
            ) : null}
          </div>
          {relationType === "many-to-one" || relationType === "one-to-one" ? (
            <div>
              <FieldLabel htmlFor={`${idPrefix}-relation-ondelete`}>
                {t("dataModels.onDelete", { defaultValue: "On Delete" })}
              </FieldLabel>
              <Select
                id={`${idPrefix}-relation-ondelete`}
                className={selectClassName}
                value={field.relation?.onDelete ?? "restrict"}
                onChange={(event) =>
                  updateRelation({
                    onDelete: event.target.value as
                      | "restrict"
                      | "cascade"
                      | "nullify",
                  })
                }
              >
                <option value="restrict">
                  {t("dataModels.onDeleteOptions.restrict", {
                    defaultValue: "Restrict (block delete)",
                  })}
                </option>
                <option value="cascade">
                  {t("dataModels.onDeleteOptions.cascade", {
                    defaultValue: "Cascade (delete referencing records)",
                  })}
                </option>
                <option value="nullify">
                  {t("dataModels.onDeleteOptions.nullify", {
                    defaultValue: "Set null (clear reference)",
                  })}
                </option>
              </Select>
              <Text className="text-muted-foreground mt-1 text-sm">
                {t("dataModels.onDeleteHint", {
                  defaultValue:
                    "What happens to this record when the referenced record is deleted.",
                })}
              </Text>
            </div>
          ) : null}
        </div>
      ) : null}

      {field.type === "number" ? (
        <>
          <div>
            <FieldLabel htmlFor={`${idPrefix}-number-kind`}>
              {t("dataModels.numberKind")}
            </FieldLabel>
            <Select
              id={`${idPrefix}-number-kind`}
              className={selectClassName}
              value={field.numberKind ?? "decimal"}
              onChange={(event) =>
                update({
                  numberKind: event.target.value as "integer" | "decimal",
                })
              }
            >
              <option value="decimal">
                {t("dataModels.numberKinds.decimal")}
              </option>
              <option value="integer">
                {t("dataModels.numberKinds.integer")}
              </option>
            </Select>
          </div>
          <div>
            <FieldLabel htmlFor={`${idPrefix}-display-format`}>
              {t("dataModels.numberDisplayFormat")}
            </FieldLabel>
            <Select
              id={`${idPrefix}-display-format`}
              className={selectClassName}
              value={field.ui?.displayFormat ?? "plain"}
              onChange={(event) =>
                updateUi({
                  displayFormat: event.target.value as
                    | "currency"
                    | "plain"
                    | "percentage",
                })
              }
            >
              <option value="plain">
                {t("dataModels.numberDisplayFormats.plain")}
              </option>
              <option value="currency">
                {t("dataModels.numberDisplayFormats.currency")}
              </option>
              <option value="percentage">
                {t("dataModels.numberDisplayFormats.percentage")}
              </option>
            </Select>
          </div>
        </>
      ) : null}

      {field.type === "date" ? (
        <div>
          <FieldLabel htmlFor={`${idPrefix}-date-display-format`}>
            {t("dataModels.dateDisplayFormat")}
          </FieldLabel>
          <Select
            id={`${idPrefix}-date-display-format`}
            className={selectClassName}
            value={field.ui?.dateDisplayFormat ?? "datetime"}
            onChange={(event) =>
              updateUi({
                dateDisplayFormat: event.target.value as
                  | "date"
                  | "datetime"
                  | "time",
              })
            }
          >
            <option value="date">
              {t("dataModels.dateDisplayFormats.date")}
            </option>
            <option value="datetime">
              {t("dataModels.dateDisplayFormats.datetime")}
            </option>
            <option value="time">
              {t("dataModels.dateDisplayFormats.time")}
            </option>
          </Select>
        </div>
      ) : null}

      {field.type === "image" ? (
        <FieldFileMetadataEditor
          field={field}
          entityName={entityName}
          onChange={onChange}
          showDefaultImage
        />
      ) : null}

      {field.type === "document" ? (
        <FieldFileMetadataEditor
          field={field}
          entityName={entityName}
          onChange={onChange}
        />
      ) : null}
    </div>
  );
}

function FieldFileMetadataEditor({
  field,
  entityName,
  onChange,
  showDefaultImage = false,
}: {
  readonly field: FieldDefinitionInput;
  readonly entityName?: string;
  readonly onChange: (field: FieldDefinitionInput) => void;
  readonly showDefaultImage?: boolean;
}) {
  const { t } = useTranslation("common");
  const idPrefix = useId().replace(/:/g, "");
  const [uploadingDefault, setUploadingDefault] = useState(false);

  const defaultMaxBytes =
    field.type === "image"
      ? DEFAULT_IMAGE_MAX_SIZE_BYTES
      : DEFAULT_DOCUMENT_MAX_SIZE_BYTES;
  const effectiveMaxBytes = resolveFileFieldMaxSizeBytes(
    field.type === "image" ? "image" : "document",
    field.maxSizeBytes,
  );
  const resolvedFieldName = resolveFieldDefinitionName(field);
  const defaultImageRef = isEntityFileReferenceWithDownload(field.defaultImage)
    ? field.defaultImage
    : null;

  async function handleDefaultImageUpload(params: {
    readonly file: File;
    readonly uploadId: string;
  }) {
    if (!entityName?.trim() || !resolvedFieldName) {
      toast.error(t("dataModels.defaultImageRequiresEntityName"));
      return;
    }

    setUploadingDefault(true);
    try {
      const data = await readFileAsBase64(params.file);
      const file = await uploadEntityFile({
        entityName: entityName.trim(),
        fieldName: resolvedFieldName,
        contentType: params.file.type || "image/jpeg",
        fileName: params.file.name,
        data,
        purpose: "fieldDefault",
      });
      onChange({ ...field, defaultImage: file });
      toast.success(t("entity.fileUploadSuccess"));
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : t("entity.fileUploadFailed"),
      );
      throw error;
    } finally {
      setUploadingDefault(false);
    }
  }

  return (
    <div className="space-y-4">
      <div>
        <FieldLabel htmlFor={`${idPrefix}-max-size-mb`}>
          {t("dataModels.maxFileSizeMb")}
        </FieldLabel>
        <Input
          id={`${idPrefix}-max-size-mb`}
          type="number"
          min={0.1}
          step={0.1}
          placeholder={formatMaxSizeMb(defaultMaxBytes)}
          value={formatMaxSizeMb(field.maxSizeBytes)}
          onChange={(event) => {
            const maxSizeBytes = parseMaxSizeMb(event.target.value);
            onChange({
              ...field,
              maxSizeBytes,
            });
          }}
        />
        <Text className="text-muted-foreground mt-1 text-sm">
          {field.type === "image"
            ? t("dataModels.imageFieldHint", {
                maxSizeMb: formatMaxSizeMb(effectiveMaxBytes),
              })
            : t("dataModels.documentFieldHint", {
                maxSizeMb: formatMaxSizeMb(effectiveMaxBytes),
              })}
        </Text>
      </div>

      {showDefaultImage ? (
        <div>
          <FieldLabel>{t("dataModels.defaultImage")}</FieldLabel>
          <Text className="text-muted-foreground mb-2 text-sm">
            {t("dataModels.defaultImageHint")}
          </Text>
          {!entityName?.trim() || !resolvedFieldName ? (
            <Text className="text-muted-foreground text-sm">
              {t("dataModels.defaultImageRequiresEntityName")}
            </Text>
          ) : (
            <div className="flex flex-col gap-2">
              <PhotoUpload
                value={defaultImageRef?.downloadUrl ?? null}
                alt={t("dataModels.defaultImage")}
                uploading={uploadingDefault}
                maxSizeBytes={effectiveMaxBytes}
                dialogLayer="nested"
                labels={imagePhotoUploadLabels(t)}
                onUpload={handleDefaultImageUpload}
                onError={(message) => toast.error(message)}
              />
              {field.defaultImage ? (
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="self-start"
                  onClick={() =>
                    onChange({
                      ...field,
                      defaultImage: undefined,
                    })
                  }
                >
                  {t("dataModels.clearDefaultImage")}
                </Button>
              ) : null}
            </div>
          )}
        </div>
      ) : null}
    </div>
  );
}
